dist: xenial
sudo: required
services:
  - docker

language: go
go:
  - "1.11.x"
  - "1.12.x"
  - "1.13.x"
  - tip

install:
  - make tools

script:
  - make lint
  - make test
  - make test-build-all
  - make website-lint
  - make website-test

branches:
  only:
    - master

matrix:
  fast_finish: true
  allow_failures:
    - go: tip

env:
  global: GOFLAGS=-mod=vendor
